<AdminProductView>:
    name: "admin_product_info"

    MDGridLayout:
        cols: 1

        MDToolbar:
            title: "Products Information"
            halign: "center"
            md_bg_color: [150/255,200/255,150/255,255/255]
            id: layout
            elevation: 15
            left_action_items: [["arrow-left", lambda x: root.manager.callback("admin", "right"), "Back"]]

        ScrollView:
            MDList:
                id: admin_product_info_list