<AdminCustomerInfo>:
    name: "admin_customer_info"

    MDGridLayout:
        cols: 1

        MDToolbar:
            title: "Customers Information"
            halign: "center"
            id: layout
            elevation: 15
            left_action_items: [["arrow-left", lambda x: root.manager.callback("admin", "right"), "Back"]]

        ScrollView:
            MDList:
                id: admin_customer_info_list